#include "..\script_component.hpp";
/*
 * Author: CW3.Sparrow.P
 * This function handles placement of smoke for different tasks
 *
 * Arguments:
 * 0: Location <OBJECT>
 *
 * Return Value:
 * Nothing
 *
 * Example:
 * call rScripts_fnc_vic_startaction;
 *
 * Public: No
 */

// Initialize variables
_AAA_VIC_Array=[["UK3CB_AAF_O_2S6M_Tunguska","Tunguska","Radar Guided Gun with Radar Guided Missiles. Radar Range is about 8km"] 
,["UK3CB_AAF_O_MTLB_ZU23","MTLB with ZU-23","MTLB with a ZU-23 Turret on top. Effective Range is 1.5km"] 
,["UK3CB_AAF_O_ZsuTank","Shilka","Radar Guided Gun with Quad 23mm barrels. Uses a shotgun like spread to hit targets. Radar Range is about 2km"]
,["UK3CB_AAF_O_Igla_AA_pod","Djigit (Igla Turret)","Turret that uses the igla launcher to lock onto the IR signature of aircraft. Range is about 2km" ]
,["UK3CB_AAF_O_ZU23","ZU-23 Turret","23mm anti-aircraft gun with twin barrels. This has been taken and slapped on every manner of vehicle"]
,["UK3CB_CHD_O_Fishing_Boat_Zu23_front","Fishing Boat with ZU-23","Fishing boat with a ZU-23 Turret on top. Effective Range is 1.5km" ]
,["UK3CB_ADA_O_Pickup_ZU23","Pickup with ZU-23","Pickup with a ZU-23 Turret on top. Effective Range is 1.5km" ]
,["PRACS_SLA_S60","S-60 Cannon","57mm Anti-Aircraft Cannon" ]
,["PRACS_SLA_ZPU4","ZPU-4 Turret","Quad .50 Cal Anti-Aircraft Turret"] 
,["PRACS_SLA_SA9","SA-9", "BRDM with Anti-Air Missile system on top." ]
,["PRACS_SLA_SA8","SA-8","Radar Guided Missile Launcher wit radar Range of 16kms" ]
,["PRACS_SLA_SA17","SA-17","SA-17 Snowdrift with radar range of 20km. Will kill you about you see it"] 
]; 
_Tanks_VIC_Array=[["UK3CB_AAF_O_2S1","2S1 SPG","Self-Propelled Howitzer introduced in 1972. Based on the MT-LBu mutli-prupose chassis"] 
,["UK3CB_AAF_O_Kamaz_MLRS", "Kamaz MLRS", "Russian Truck with a Multi-Launcher Rocket System (MLRS)"] 
,["UK3CB_AAF_O_MAZ_543_SCUD", "MAZ 543 SCUD Launcher", "Russian Vechile designed to carry SCUD missiles"] 
,["UK3CB_AAF_O_BM21", "Ural 4320 (BM-21 Grad)", "Russian Truck with a Multi-Launcher Rocket System (MLRS)"]  
,["UK3CB_AAF_O_D30", "2A18M (D-30A)", "Russian Artillery Piece"]  
,["UK3CB_AAF_O_2b14_82mm", "2B14-1 'Podnos'", "Russian Mortar Piece"]   
,["UK3CB_AAF_O_T55", "T-55A","The T-55A tank is a Soviet-era armored vehicle renowned for its robustness and adaptability, serving as a mainstay in numerous conflicts since its introduction in the 1950s. With a potent 100mm rifled gun and thick frontal armor, it posed a formidable threat on the battlefield during its prime, embodying the Soviet doctrine of simple yet effective armored warfare. Despite its age, the T-55A remains in service with various nations worldwide, a testament to its enduring design and battlefield prowess."] 
,["UK3CB_AAF_O_T72BB","T-72BB","The T-72BB, an upgraded variant of the iconic Soviet T-72 main battle tank, epitomizes modern armored warfare with its blend of firepower, protection, and mobility. Armed with a powerful 125mm smoothbore gun and equipped with advanced composite armor, it offers enhanced lethality and survivability on the battlefield. With continuous upgrades and widespread adoption by various nations, the T-72BB remains a formidable force, ensuring its relevance in contemporary armored operations."] 
,["UK3CB_ADA_O_T34","T-34-85M","The T-34-85M stands as a modified version of the legendary T-34 tank, revered for its pivotal role in World War II. Featuring a larger turret housing an 85mm gun, it boasted improved firepower and performance compared to its predecessor. Renowned for its simplicity, ruggedness, and significant contribution to the Soviet victory, the T-34-85M remains a symbol of resilience and effectiveness in armored warfare."] 
,["UK3CB_CW_SOV_O_EARLY_T80","T-80","The T-80, a pinnacle of Soviet tank engineering, showcases cutting-edge technology with its gas turbine engine and advanced fire control systems. Its hallmark feature, the gas turbine engine, provides exceptional power-to-weight ratio, granting it superior speed and maneuverability on the battlefield. Armed with a formidable 125mm smoothbore gun and layered with composite armor, the T-80 exemplifies a potent combination of firepower and protection, solidifying its status as a formidable force in modern armored warfare."]
,["UK3CB_CW_SOV_O_LATE_T80U","T-80U","The T-80U, an upgraded iteration of the T-80 series, represents the pinnacle of Soviet/Russian tank design, boasting advanced features such as a more powerful gas turbine engine and sophisticated reactive armor. With its 125mm smoothbore gun and advanced fire control systems, it delivers unparalleled lethality and accuracy on the battlefield. Renowned for its exceptional mobility, formidable firepower, and robust protection, the T-80U remains a cornerstone of modern armored forces, ensuring its continued relevance in contemporary warfare scenarios."] 
]; 
_BMD_BMP_BTR_M113_MTLB_VIC_Array=[["UK3CB_CHD_O_BMD1","BMD-1","The BMD-1, a Soviet airborne infantry fighting vehicle, revolutionized airborne operations with its unique combination of firepower and mobility. Armed with a 73mm smoothbore gun and a coaxial machine gun, it provided effective fire support for airborne troops while maintaining the ability to be airdropped or transported by air. Its amphibious capability further enhanced its versatility, making it a vital asset for rapid deployment and maneuverability in various combat environments."] 
,["UK3CB_CHD_O_BMD1K","BMD-1K","The BMD-1K, a command variant of the BMD-1 airborne infantry fighting vehicle, served as a vital link in coordinating operations for airborne units. Equipped with additional communication equipment and antennas, it facilitated efficient command and control on the battlefield, enabling swift and coordinated maneuvers. Combining the mobility and firepower of the BMD-1 with enhanced command capabilities, the BMD-1K played a crucial role in supporting airborne forces in executing their missions with precision and agility."] 
,["UK3CB_AAF_O_BMP2K","BMP-2K","The BMD-2K, a command variant derived from the BMD-2 airborne infantry fighting vehicle, served as a mobile command post for airborne units, integrating advanced communication systems and command equipment. With its enhanced situational awareness capabilities and communication infrastructure, it facilitated efficient coordination and control of operations in dynamic battlefield environments. By combining the agility and firepower of the BMD-2 with specialized command functionalities, the BMD-2K played a pivotal role in ensuring effective command and control for airborne forces during rapid deployments and maneuver warfare scenarios."] 
,["UK3CB_AAF_O_BTR60","BTR-60","The BTR-60 is a Soviet-made armored personnel carrier (APC) known for its amphibious capabilities and robust design. Equipped with a crew of two and capable of carrying up to 14 fully equipped troops, it provided essential transportation and protection for infantry units. With its 14.5mm heavy machine gun and 7.62mm coaxial machine gun, the BTR-60 offered fire support during troop transport and combat operations, making it a versatile asset for mechanized infantry forces."] 
,["UK3CB_AAF_O_BTR80","BTR-80","The BTR-80 is an iconic Russian armored personnel carrier (APC), renowned for its versatility, mobility, and ruggedness. Designed to transport troops swiftly and safely across varied terrains, it accommodates up to 10 fully equipped soldiers along with a crew of three. Armed with a 14.5mm heavy machine gun and a 7.62mm coaxial machine gun, it provides effective fire support during combat operations. With its amphibious capability, the BTR-80 ensures seamless movement across both land and water, making it an indispensable asset for modern mechanized forces."]  
,["UK3CB_AAF_O_BTR80a","BTR-80a","The BTR-80A is an upgraded version of the iconic Russian armored personnel carrier (APC), featuring enhanced protection, firepower, and mobility. Equipped with advanced armor plating and additional reactive armor modules, it offers improved survivability against modern threats on the battlefield. With its formidable armament, including a 30mm automatic cannon and a coaxial machine gun, the BTR-80A provides increased firepower to support troops during combat operations. Renowned for its versatility and reliability, the BTR-80A remains a cornerstone of modern mechanized infantry forces, ensuring swift and secure transportation of troops in various operational environments."] 
,["UK3CB_ADA_O_BTR40_MG","BTR-40","The BTR-40 is a Soviet-made armored personnel carrier (APC) characterized by its simplicity, reliability, and ruggedness. Designed for both on-road and off-road operations, it provided transportation for infantry units in various terrains. Armed with a single 7.62mm machine gun, it offered basic fire support during troop transport and light combat engagements. Despite its age, the BTR-40's versatility and durability made it a valuable asset for infantry forces, particularly in reconnaissance and support roles."] 
,["UK3CB_AAF_O_M113_M2","M113 with M2","The M113 with M2 refers to the M113 armored personnel carrier equipped with an M2 Browning .50 caliber machine gun. This configuration enhances the M113's firepower, making it suitable for providing heavy suppressive fire and engaging armored and fortified targets. With the M2 Browning, a reliable and powerful weapon, mounted on the M113, it significantly increases the vehicle's combat effectiveness, enabling it to support infantry units in various combat scenarios, including convoy protection, perimeter defense, and urban operations."] 
,["UK3CB_AAF_O_M113_MK19","M113 with MK19","The M113 with MK19 refers to the M113 armored personnel carrier outfitted with an MK19 automatic grenade launcher. This configuration significantly enhances the vehicle's firepower, allowing it to deliver devastating explosive rounds with high accuracy and rapid rate of fire. The MK19-equipped M113 is particularly effective in providing fire support during infantry operations, suppressing enemy positions, and engaging light armored vehicles and fortified targets. This combination of the M113's mobility and protection with the MK19's firepower makes it a versatile asset for a wide range of combat scenarios, including convoy escort, urban warfare, and defensive operations."]  
,["UK3CB_AAF_O_MTLB_Cannon","MT-LB (30mm Cannon)","The MT-LB with a 30mm cannon refers to the MT-LB armored personnel carrier modified to mount a 30mm autocannon. This configuration enhances the vehicle's firepower, allowing it to engage a variety of targets, including light armored vehicles, infantry positions, and fortifications, with increased lethality and accuracy. With its versatility, mobility, and armored protection, the MT-LB with a 30mm cannon serves as a potent asset for supporting infantry units, conducting reconnaissance missions, and providing fire support in various combat environments, including urban areas and open terrain."] 
,["UK3CB_AAF_O_MTLB_KPVT","MT-LB (KPVT)","The MT-LB with KPVT refers to the MT-LB armored personnel carrier equipped with a KPVT heavy machine gun. This configuration enhances the vehicle's firepower, providing it with a powerful weapon capable of engaging light armored vehicles, infantry, and other soft targets with high-caliber ammunition. With the KPVT heavy machine gun, known for its reliability and penetration capability, the MT-LB becomes an effective fire support platform for infantry units, convoy protection, and perimeter defense. Its mobility, versatility, and armored protection make it a valuable asset in various combat scenarios, including reconnaissance missions and counter-insurgency operations."]  
]; 
_BRDM_TIG_VODNIK_URAL_PRAGA_VIC_Array=[["UK3CB_AAF_O_BRDM2","BRDM-2","The BRDM-2, an iconic Soviet-made armored reconnaissance and patrol vehicle, is known for its exceptional mobility and versatility. Armed with a 14.5mm KPVT heavy machine gun and a 7.62mm PKT coaxial machine gun, it provides effective firepower for reconnaissance missions and border patrol duties. With its amphibious capability, the BRDM-2 can traverse water obstacles, further expanding its operational range. Renowned for its reliability and ruggedness, the BRDM-2 remains in service with numerous countries worldwide, showcasing its enduring legacy as a staple of reconnaissance and security forces."] 
,["UK3CB_AAF_O_BRDM2_ATGM", "BRDM-2 (Konkurs)","The BRDM-2 (Konkurs) variant is an upgraded version of the iconic Soviet-made armored reconnaissance and patrol vehicle, featuring the addition of the Konkurs anti-tank guided missile system. This enhancement significantly augments its firepower, enabling it to engage armored targets with precision and lethality at extended ranges. With the Konkurs missile system, capable of defeating heavily armored vehicles, the BRDM-2 (Konkurs) serves as a potent asset for reconnaissance and anti-armor missions. Its combination of mobility, reconnaissance capabilities, and anti-tank firepower makes it a versatile and effective platform in modern battlefield scenarios."]
,["UK3CB_AAF_O_BRDM2_HQ","BRDM-2UM (Armed)","The BRDM-2UM (Armed) variant is a modernized version of the classic Soviet-made armored reconnaissance and patrol vehicle, featuring enhanced firepower and capabilities. Equipped with various armament options such as machine guns, automatic cannons, or anti-tank guided missiles, it provides increased versatility for a wide range of combat scenarios. With its upgraded reconnaissance systems and improved mobility, the BRDM-2UM (Armed) excels in reconnaissance missions, border patrol, and providing fire support for infantry units. Its robust design and modern upgrades ensure its effectiveness and relevance on the battlefield in contemporary military operations."] 
,["UK3CB_ADA_O_V3S_Reammo","Praga V3S (Ammo)","The Praga V3S is a robust, multipurpose truck produced in Czechoslovakia, renowned for its durability and versatility. Initially designed for military applications, it served as a cargo transport vehicle, capable of navigating rough terrain and adverse weather conditions with ease. With its sturdy construction and reliable performance, the Praga V3S found applications beyond military use, including civilian logistics, firefighting, and construction. Its enduring legacy as a dependable workhorse reflects its importance in various industries and its contribution to transportation capabilities in both military and civilian sectors."] 
,["UK3CB_AAF_O_Tigr_STS","GAZ Tigr (Armed)","The GAZ Tigr (Armed) is a versatile light armored vehicle developed by Russia, renowned for its agility, mobility, and firepower. Equipped with various armament configurations such as machine guns, grenade launchers, or anti-tank guided missiles, it offers potent firepower for reconnaissance, patrol, and combat missions. Its agile off-road capabilities, coupled with robust armor protection, make it suitable for operating in diverse terrain and hostile environments. With its modular design and adaptability, the GAZ Tigr (Armed) serves as a vital asset for modern military and security forces, ensuring effectiveness in a wide range of operational scenarios."] 
,["UK3CB_AAF_O_Ural","Ural 4320 (Closed)","The Ural 4320 is a rugged and versatile military truck produced by the Russian automotive manufacturer Ural Automotive Plant. Renowned for its reliability and off-road capabilities, it has been widely used for various military and civilian applications, including troop transport, cargo logistics, and mobile workshop operations. With its robust construction and powerful engine, the Ural 4320 is capable of traversing challenging terrains and adverse weather conditions, making it a dependable workhorse in demanding environments. Its versatility and durability have cemented its status as one of the most iconic and widely used military trucks in Russia and other countries around the world."] 
,["UK3CB_AAF_O_GAZ_Vodnik_Cannon","GAZ Vodnik (Cannon 30mm)","The GAZ Vodnik (Cannon 30mm) variant is an upgraded version of the GAZ Vodnik multipurpose armored vehicle, featuring the installation of a 30mm autocannon. This enhancement significantly increases its firepower, enabling it to engage a wide range of targets with precision and lethality. With its robust armor protection, off-road capabilities, and potent armament, the GAZ Vodnik (Cannon 30mm) excels in providing fire support for infantry units, convoy protection, and anti-armor missions. Its versatility and effectiveness make it a valuable asset for modern military and security forces operating in various operational environments."] 
,["UK3CB_AAF_O_GAZ_Vodnik_KVPT","GAZ Vodnik (KVPT)","The GAZ Vodnik (KPVT) variant is an upgraded version of the GAZ Vodnik multipurpose armored vehicle, featuring the installation of a KPVT heavy machine gun. This enhancement significantly boosts its firepower, enabling it to engage light armored vehicles, infantry, and other soft targets effectively. With its agile mobility, robust armor protection, and potent armament, the GAZ Vodnik (KPVT) excels in reconnaissance missions, border patrol, and providing fire support for infantry units. Its adaptability and reliability make it a valuable asset for modern military and security forces operating in diverse operational environments."]
,["UK3CB_AAF_O_GAZ_Vodnik_PKT","GAZ Vodnik (PKT)","The GAZ Vodnik (PKT) variant is an iteration of the GAZ Vodnik multipurpose armored vehicle equipped with a PKT coaxial machine gun. This configuration enhances its firepower, providing effective suppressive fire against infantry and light vehicles. With its agility, mobility, and armored protection, the GAZ Vodnik (PKT) excels in reconnaissance missions, convoy escort, and urban operations. Its versatility and reliability make it a valuable asset for modern military and security forces requiring a flexible and capable armored vehicle platform."] 
,["UK3CB_AAF_O_GAZ_Vodnik","GAZ Vodnik (Unarmed)","The GAZ Vodnik (Unarmed) variant is a multipurpose armored vehicle designed for various utility and transport roles. Without any mounted weaponry, it prioritizes mobility, versatility, and protection. It serves as a reliable platform for personnel transport, cargo logistics, and reconnaissance missions in both military and civilian applications. With its robust construction and off-road capabilities, the GAZ Vodnik (Unarmed) provides essential support for troops, law enforcement agencies, and emergency response teams in diverse operational environments."]
,["UK3CB_AAF_O_BRDM2_UM","BRDM-2UM (Unarmed)","The BRDM-2UM (Unarmed) variant is a modernized version of the classic BRDM-2 armored reconnaissance and patrol vehicle, configured without any mounted weaponry. This version prioritizes reconnaissance and utility roles, focusing on mobility, situational awareness, and personnel transport. With upgraded reconnaissance systems and improved mobility, the BRDM-2UM (Unarmed) excels in reconnaissance missions, border patrol, and providing support for military and security forces in various operational scenarios. Its versatility and reliability make it a valuable asset for modern military and security operations requiring a flexible and adaptable armored vehicle platform."]  
]; 
_HELO_VIC_Array=[["UK3CB_AAF_O_Bell412_Utility","CH-146 Griffin","The CH-146 Griffin is a versatile utility helicopter utilized by the Canadian Armed Forces for a wide range of missions, including troop transport, reconnaissance, search and rescue, and medical evacuation. Based on the Bell 412EP platform, it features enhanced performance capabilities, including increased payload capacity and improved range. Equipped with advanced avionics and mission systems, the CH-146 Griffin provides essential support to ground forces and contributes to Canada's military operations at home and abroad. Its versatility and reliability make it a valuable asset for various military and humanitarian missions, showcasing its importance in Canada's defense and security efforts."] 
,["UK3CB_AAF_O_Bell412_Armed","CH-146 Griffin (Gunship)","The CH-146 Griffin Gunship variant is a modified version of the utility helicopter utilized by the Canadian Armed Forces, equipped with additional weaponry for close air support and fire support missions. Typically armed with machine guns, rockets, and possibly anti-tank missiles, it enhances the helicopter's firepower to engage ground targets effectively. The CH-146 Griffin Gunship provides essential support to ground forces during combat operations, reconnaissance missions, and counter-insurgency efforts, contributing to Canada's military capabilities in complex and dynamic environments. Its versatility and adaptability make it a valuable asset for providing lethal support and enhancing the effectiveness of ground troops in various operational scenarios."]  
,["UK3CB_AAF_O_Mi_24V","Mil Mi-24V","The Mil Mi-24V, a variant of the iconic Russian helicopter, is a formidable attack helicopter renowned for its firepower, armor protection, and troop-carrying capabilities. Equipped with a powerful combination of guns, rockets, and anti-tank missiles, it serves as a lethal platform for close air support, anti-tank missions, and aerial firefights. With its distinctive tandem cockpit layout and heavily armored fuselage, the Mi-24V provides excellent protection for its crew while delivering devastating firepower to enemy targets. Its versatility and combat effectiveness make it a cornerstone of many military forces worldwide, ensuring air superiority and ground support in diverse combat environments."] 
,["UK3CB_AAF_O_Mi8AMTSh","Mil Mi-8 (Rockets)","The Mil Mi-8, a versatile Russian helicopter, can be configured with rocket pods to enhance its combat capabilities. Typically armed with S-5 or S-8 rockets, it becomes a potent aerial platform for engaging ground targets, including enemy personnel, light vehicles, and fortified positions. The Mi-8's ability to carry a significant payload of rockets enables it to provide effective fire support for ground forces during combat operations, reconnaissance missions, and anti-insurgency efforts. Its adaptability and reliability make it a valuable asset for various military forces worldwide, ensuring firepower and mobility in dynamic battlefield environments."] 
,["RHS_Ka52_vvsc","Ka-52","The Kamov Ka-52 'Alligator' is a twin-seat, all-weather attack helicopter developed by Russia, known for its formidable firepower, advanced avionics, and maneuverability. Armed with a 30mm cannon, guided missiles, and rockets, it is optimized for anti-armor and anti-personnel missions, capable of engaging multiple targets simultaneously. Equipped with a modern suite of sensors, including radar, electro-optical systems, and countermeasure systems, the Ka-52 provides excellent situational awareness and survivability on the battlefield. Its coaxial rotor design offers exceptional agility and stability, allowing it to operate effectively in diverse combat scenarios, including close air support, reconnaissance, and anti-ship operations. Renowned for its combat effectiveness and reliability, the Ka-52 represents a formidable asset in modern aerial warfare."]
,["rhs_mi28n_vvsc","Mi-28N","The Mil Mi-28N 'Havoc' is a dedicated attack helicopter developed by Russia, renowned for its firepower, armor protection, and night-fighting capabilities. Armed with a 30mm cannon, guided missiles, and rockets, it serves as a formidable platform for engaging armored vehicles, infantry, and fortified positions on the battlefield. Equipped with advanced avionics and sensor systems, including night vision goggles and thermal imaging, the Mi-28N excels in low-light and adverse weather conditions, providing round-the-clock combat effectiveness. Its heavily armored cockpit and fuselage offer enhanced crew protection, ensuring survivability in high-threat environments. With its versatility and combat effectiveness, the Mi-28N plays a crucial role in supporting ground forces and conducting anti-armor missions in modern warfare scenarios."] 
,["rhs_ka60_c","Ka-60","The Kamov Ka-60 Kasatka is a versatile utility helicopter developed by Russia, designed for a wide range of missions including troop transport, search and rescue, medical evacuation, and VIP transportation. Characterized by its twin-engine design and spacious cabin, the Ka-60 offers excellent performance, reliability, and flexibility in various operational environments. With its modular interior layout, it can accommodate troops, cargo, or specialized equipment, making it adaptable to different mission requirements. Equipped with advanced avionics and navigation systems, the Ka-60 provides enhanced situational awareness and operational efficiency for both military and civilian operators. Its versatility and reliability make it a valuable asset for various applications, ranging from military logistics to civilian transportation and emergency response."] 
]; 
_PLANE_VIC_Array=[["UK3CB_AAF_O_Cessna_T41_Armed_Bombs","T-41 Mescalero CAS (Bombs)","The T-41 Mescalero CAS, also known as the Cessna T-41, is a light aircraft primarily used for training purposes. It is not typically equipped for combat missions, such as close air support (CAS), and does not have provisions for carrying bombs. Instead, it is primarily used for pilot training, reconnaissance, and liaison duties. While modifications are possible, such as adding hardpoints for weapons, the T-41 is not commonly used in combat roles due to its limited payload capacity and lack of armor protection."] 
,["UK3CB_AAF_O_Cessna_T41_Armed_M2","T-41 Mescalero CAS (M2)","The T-41 Mescalero CAS, also known as the Cessna T-41, is a light aircraft primarily used for training purposes and is not typically equipped with weaponry such as the M2 Browning machine gun. The M2 Browning is a heavy machine gun commonly mounted on military vehicles, aircraft, and naval vessels for offensive purposes. While modifications are possible, such as adding hardpoints for weapons, the T-41 is not commonly used in combat roles due to its limited payload capacity and lack of armor protection. Therefore, the combination of the T-41 Mescalero and the M2 Browning is not a standard configuration." ] 
,["UK3CB_AAF_O_MIG29SM", "MIG-29SM","The MiG-29SM is a modernized variant of the renowned MiG-29 fighter aircraft, featuring upgrades to its avionics, weapons systems, and airframe to enhance its combat capabilities. These upgrades typically include improved radar, avionics, and compatibility with advanced air-to-air and air-to-ground weapons. The 'SM' designation usually denotes a 'Super Modernized' version, indicating significant improvements over earlier variants. With its enhanced performance and versatility, the MiG-29SM remains a potent air superiority fighter capable of engaging a wide range of aerial threats in modern combat scenarios."] 
,["UK3CB_AAF_O_Su25SM","Su-25SM","The Su-25SM is an upgraded variant of the legendary Su-25 close air support aircraft, designed to provide increased combat capabilities and versatility on the battlefield. It features modernized avionics, improved survivability systems, and enhanced weapon compatibility, allowing it to perform a wide range of missions with greater precision and effectiveness. The 'SM' designation typically denotes 'Modernized' or 'Super Modernized,' indicating significant enhancements over earlier versions.Equipped with advanced targeting systems and updated weapon systems, the Su-25SM can engage ground targets with precision-guided munitions and air-to-ground missiles. Its robust airframe and armored protection make it highly resilient to enemy fire, allowing it to operate effectively in high-threat environments. With its upgraded capabilities, the Su-25SM remains a formidable asset for close air support, battlefield interdiction, and counterinsurgency operations."] 
,["UK3CB_AAF_O_Su25SM_KH29","Su-25SM (KH29)","The Su-25SM is an upgraded variant of the legendary Su-25 close air support aircraft, enhanced with modernized avionics, improved survivability systems, and advanced weapon compatibility. When equipped with the KH-29 air-to-surface missile (sometimes denoted as 'KH-29'), the Su-25SM gains the capability to engage ground targets with precision and long-range standoff capabilities. The KH-29 missile, with its guided system, enables the Su-25SM to strike high-value targets such as enemy armored vehicles, bunkers, and fortified positions with accuracy and lethality, further enhancing its effectiveness in modern combat scenarios."]  
,["UK3CB_CW_SOV_O_EARLY_MIG21_CAS", "Mig-21 (CAS)","The MiG-21, a renowned Soviet-era fighter aircraft, is not traditionally used in the close air support (CAS) role due to its design and limitations. While it excels in air-to-air combat, it lacks the robust armor protection, advanced avionics, and weapon systems typically required for effective CAS missions. However, in some conflict zones or under specific circumstances, modified versions of the MiG-21 may be adapted for limited ground attack roles, employing unguided rockets, bombs, or gun pods against soft targets. Nonetheless, its primary role and design focus remain air-to-air combat, interception, and aerial superiority."] 
]; 
_CARS_VIC_Array=[["UK3CB_AAF_O_SUV_Armed", "SUV 4x4 Armed (M134)","The term 'SUV 4x4 Armed (M134)' suggests a 4x4 sport utility vehicle (SUV) that has been modified to incorporate an M134 Minigun. The M134 Minigun is a six-barreled rotary machine gun capable of firing a high volume of ammunition at an extremely rapid rate, typically used for suppressive fire and anti-personnel purposes.When mounted on an SUV, the M134 provides significant firepower, making it suitable for various roles such as convoy escort, perimeter defense, and counter-terrorism operations. The mobility and versatility of the SUV platform, combined with the firepower of the M134 Minigun, create a formidable asset for military and law enforcement units requiring rapid response and high firepower in dynamic environments." ]
,["UK3CB_AAF_O_LR_SF_M2", "Land Rover WMIK (HMG)","The Land Rover WMIK (HMG) refers to the 'Weapons Mount Installation Kit' variant of the Land Rover Defender, equipped with a heavy machine gun (HMG). Typically, this includes the Browning M2 .50 caliber machine gun or similar weapons mounted on a pedestal in the rear bed of the vehicle.Used primarily by military forces for reconnaissance, patrol, and fire support roles, the Land Rover WMIK (HMG) provides mobility and firepower to engage enemy personnel and light vehicles. Its compact size and off-road capabilities make it well-suited for maneuvering in various terrains, including urban environments and rugged terrain. The combination of the Land Rover platform and the heavy machine gun enhances the vehicle's versatility and effectiveness in combat operations."] 
,["UK3CB_ADA_O_Hilux_Dshkm", "Hilux (DHSKM)","The Hilux (DShK) refers to the Toyota Hilux pickup truck modified to mount a DShK heavy machine gun. The DShK, also known as Dushka, is a Soviet-made heavy machine gun known for its reliability and firepower. When mounted on the Hilux, it provides significant firepower for various roles, including convoy escort, perimeter defense, and counter-insurgency operations.The Hilux's ruggedness and off-road capabilities make it an ideal platform for military and paramilitary forces operating in diverse environments. The combination of the Hilux's mobility and the firepower of the DShK enhances the vehicle's effectiveness in providing fire support and engaging enemy targets. This configuration is commonly seen in conflict zones and areas with high security risks, where rapid response and firepower are essential for mission success." ]
,["UK3CB_ADA_O_Hilux_M2", "Hilux (M2)","The Hilux (M2) typically refers to the Toyota Hilux pickup truck modified to mount an M2 Browning .50 caliber heavy machine gun. The M2 Browning is a widely used heavy machine gun known for its reliability and firepower. When mounted on the Hilux, it provides significant firepower for various roles, including convoy escort, perimeter defense, and counter-insurgency operations.The Hilux's durability, versatility, and off-road capabilities make it an ideal platform for military and paramilitary forces operating in diverse environments. The combination of the Hilux's mobility and the firepower of the M2 Browning enhances the vehicle's effectiveness in providing fire support and engaging enemy targets. This configuration is commonly seen in conflict zones and areas with high security risks, where rapid response and firepower are essential for mission success." ]
,["UK3CB_ADA_O_Pickup_Rocket_Arty", "Pickup (Artillery)","A pickup truck modified for artillery purposes typically involves mounting artillery pieces or rocket launchers onto the bed of the truck. These modifications allow for rapid deployment and maneuverability in the field, providing flexible and mobile platforms for delivering indirect fire support in various operational environments." ]
,["UK3CB_ADA_O_Pickup_GMG","Pickup (GMG)","A pickup truck modified with a GMG, or Grenade Machine Gun, typically involves mounting this automatic grenade launcher onto a stable platform in the bed of the truck. This configuration enhances the vehicle's firepower, providing effective suppression and engagement capabilities against both personnel and light vehicles. The pickup(GMG) combination offers increased mobility and versatility, making it suitable for roles such as convoy escort, perimeter defense, and counter-insurgency operations in challenging environments." ]
,["UK3CB_ADA_O_Pickup_Rocket","Pickup (Rocket)","A pickup truck modified for rocket launchers typically involves mounting rocket launch tubes or racks onto the bed of the truck. This configuration enhances the vehicle's firepower, allowing it to deliver rockets with precision and effectiveness against various targets. The pickup (rocket) combination offers increased mobility and flexibility, making it suitable for roles such as fire support, infantry support, and quick reaction forces in both conventional and asymmetric warfare scenarios." ]
,["UK3CB_ADA_O_Pickup_SPG9","Pickup (SPG-9)","A pickup truck modified with an SPG-9, or Solntsepek, typically involves mounting this recoilless gun onto a stable platform in the bed of the truck. This configuration enhances the vehicle's firepower, providing effective anti-armor and anti-personnel capabilities. The pickup (SPG-9) combination offers increased mobility and versatility, making it suitable for roles such as infantry support, convoy protection, and counter-insurgency operations in challenging environments." ]
,["UK3CB_ADA_O_Pickup_TOW","Pickup (TOW)","A pickup truck modified with a TOW missile launcher typically involves mounting the launcher and its associated equipment onto a stable platform in the bed of the truck. This configuration enhances the vehicle's firepower, providing effective anti-armor capabilities with the precision-guided TOW missiles. The pickup (TOW) combination offers increased mobility and flexibility, making it suitable for roles such as anti-tank warfare, convoy protection, and rapid deployment in various operational environments."] 
,["UK3CB_AAF_O_UAZ_AGS30","UAZ-3151 (AGS-30)","The UAZ-3151 modified with an AGS-30 automatic grenade launcher typically involves mounting this weapon onto a stable platform in the vehicle. This configuration enhances the vehicle's firepower, offering effective suppression and engagement capabilities against infantry and light vehicles. The UAZ-3151 (AGS-30) combination provides increased mobility and flexibility, making it suitable for roles such as convoy escort, perimeter defense, and counter-insurgency operations in diverse terrain and challenging environments."] 
,["UK3CB_AAF_O_UAZ_MG","UAZ-3151 (DShKM)", "The UAZ-3151 modified with a DShK heavy machine gun typically involves mounting this weapon onto a stable platform in the vehicle. This configuration enhances the vehicle's firepower, offering effective suppression and engagement capabilities against infantry and light vehicles. The UAZ-3151 (DShKM) combination provides increased mobility and flexibility, making it suitable for roles such as convoy escort, perimeter defense, and counter-insurgency operations in diverse terrain and challenging environments."]
,["UK3CB_ADA_O_Datsun_Pickup_PKM","Datsun 620 Pickup (PKM)","The Datsun 620 Pickup modified with a PKM machine gun typically involves mounting this weapon onto a stable platform in the vehicle. This configuration enhances the vehicle's firepower, offering effective suppression and engagement capabilities against infantry and light vehicles. The Datsun 620 Pickup (PKM) combination provides increased mobility and flexibility, making it suitable for roles such as convoy escort, perimeter defense, and counter-insurgency operations in diverse terrain and challenging environments."] 
]; 
_TURRET_VIC_Array=[["UK3CB_AAF_O_Kornet","9K133-1 'Kornet-M'","The 9K133-1 'Kornet-M' is a modernized variant of the Kornet anti-tank missile system, renowned for its long-range precision and armor-penetrating capabilities. Equipped with advanced guidance systems, it can engage armored targets with high accuracy, including tanks, armored vehicles, and fortified positions. The 'Kornet-M' variant features improvements such as increased range and improved resistance to electronic countermeasures, making it a formidable asset for anti-tank warfare in modern combat scenarios."] 
,["UK3CB_AAF_O_AGS","AGS-30 (6P17)","The AGS-30, also known as the 6P17, is a modern automatic grenade launcher designed for infantry support and fire suppression. Renowned for its firepower and versatility, it can engage targets with high-explosive fragmentation grenades, providing effective suppression against enemy personnel and light vehicles. The 6P17 offers increased range and accuracy compared to older grenade launcher models, making it a valuable asset for infantry units in various combat scenarios."] 
,["UK3CB_AAF_O_DSHKM","DShKM","The DShKM is a Soviet-made heavy machine gun renowned for its reliability and firepower. Widely used by military forces around the world, it is capable of engaging infantry, light vehicles, and aircraft with its high-caliber rounds. The DShKM's robust design and ability to deliver sustained fire make it a formidable asset for ground defense, convoy protection, and anti-aircraft roles in both conventional and asymmetric warfare scenarios."] 
,["UK3CB_AAF_O_KORD","KORD (6T7)","The KORD, also known as the 6T7, is a modern heavy machine gun developed by Russia, prized for its firepower and reliability. Featuring a robust design and chambered for the powerful 12.7x108mm cartridge, it is capable of engaging infantry, light vehicles, and lightly armored targets with lethal effectiveness. The KORD's advanced features, including a quick-change barrel and enhanced recoil reduction, make it well-suited for a variety of roles, including ground defense, vehicle-mounted applications, and anti-aircraft defense." ]
,["UK3CB_AAF_O_KORD_high","KORD (6U16)","The KORD, designated as the 6U16, is a modern heavy machine gun known for its formidable firepower and reliability. Developed by Russia, it is chambered for the powerful 12.7x108mm cartridge, allowing it to engage infantry, light vehicles, and lightly armored targets with lethal effectiveness. With features such as a quick-change barrel and advanced recoil reduction mechanisms, the KORD (6U16) is suitable for various roles, including ground defense, vehicle-mounted applications, and anti-aircraft defense, ensuring its versatility and effectiveness on the battlefield."] 
,["UK3CB_AAF_O_NSV","NSV (6T7)","The NSV, also known as the 6T7, is a heavy machine gun developed by the Soviet Union, recognized for its reliability and firepower. Chambered in the 12.7x108mm caliber, it boasts the capability to engage infantry, light vehicles, and aircraft effectively. Renowned for its rugged design and high rate of fire, the NSV (6T7) is utilized in various roles, including ground defense, vehicle-mounted applications, and anti-aircraft defense, showcasing its versatility and effectiveness on the battlefield."] 
,["UK3CB_AAF_O_SPG9","SPG-9","The SPG-9 is a recoilless gun designed for infantry support and anti-tank roles, known for its simplicity, reliability, and effectiveness. Operating on the recoilless principle, it fires a variety of 73mm ammunition, including high-explosive anti-tank (HEAT) rounds and high-explosive fragmentation (HE-FRAG) rounds. The SPG-9 is prized for its ability to engage armored vehicles and fortified positions, making it a valuable asset for infantry units and irregular forces in various combat scenarios."] 
]; 









Vec_ID_Station addAction ["Anti-Air",   
       {     
       [_this select 3] call rScripts_fnc_vic_display;
       //systemChat "Action Selected";
       },_AAA_VIC_Array   
      ];  
Vec_ID_Station addAction ["Artillery and Tanks",   
       {     
      [_this select 3] call rScripts_fnc_vic_display;
       },_Tanks_VIC_Array   
      ];  
Vec_ID_Station addAction ["BMD, BMP, BTR, M113, and MTLB",   
       {     
       [_this select 3] call rScripts_fnc_vic_display;
       },_BMD_BMP_BTR_M113_MTLB_VIC_Array   
      ];  
Vec_ID_Station addAction ["BRDM, TIG, Vodnik, URAL, and Praga",   
       {     
      [_this select 3] call rScripts_fnc_vic_display;
       },_BRDM_TIG_VODNIK_URAL_PRAGA_VIC_Array   
      ]; 
Vec_ID_Station addAction ["Helicopters",   
       {     
      [_this select 3] call rScripts_fnc_vic_display;
       },_HELO_VIC_Array   
      ];
Vec_ID_Station addAction ["Planes",   
       {     
     [_this select 3] call rScripts_fnc_vic_display;
       },_PLANE_VIC_Array   
      ];
Vec_ID_Station addAction ["Cars, Land Rover, Pickup, and UAZ",   
       {     
       [_this select 3] call rScripts_fnc_vic_display;
       },_CARS_VIC_Array   
      ];
Vec_ID_Station addAction ["Turrets",   
       {     
		[_this select 3] call rScripts_fnc_vic_display;  
       },_TURRET_VIC_Array   
      ];
Vec_ID_Station addAction ["Clear Pads",   
       {     
		_location = position Vec_ID_Station;  
		_vehicles = nearestObjects [_location, ["LandVehicle","Air","StaticWeapon","Ship","Tank"], 100]; 
		{ 
    		if (count crew _x == 0) then { 
       			deleteVehicle _x; 
    		} 
		} forEach _vehicles;  
       }   
      ];